//to be fetched from backend
export const MOCK_LISTINGS_DB = [
    {
      id: "101",
      // Corrected property names to match ListingCard props
      title: "Luxury Downtown Apartment",
      description: "A beautiful and spacious apartment in the heart of the city.",
      location: "City Center, Yaoundé",
      price: "80000 FCFA",
      roomType: 'Entire Apartment',
      rooms: 3,
      toilets: 2,
      kitchen: 1,
      roommates: 0,
      size: "120 sqm", // Combined roomArea into size
      listingStyle: 'MODERN',
      // The rest of the data for the form
      listingCountry: "Cameroon",
      listingState: "Centre",
      listingCity: "Yaoundé",
      listingStreet: "123 City Center",
      isSharedBathroom: true,
      bathroomLocation: 'INDOOR',
      isSharedKitchen: false,
      imagePreviews: ["https://via.placeholder.com/400x250?text=Luxury+Apt"],
      images: [],
    },
    {
      id: "102",
      title: "Student-Friendly Room",
      description: "Perfect for students, close to the university.",
      location: "Near University, Ngoa-Ekelle",
      price: "40000 FCFA",
      roomType: "Private Room",
      rooms: 1,
      toilets: 1,
      kitchen: 1,
      roommates: 2,
      size: "20 sqm",
      listingStyle: 'CLASSIC',
      listingCountry: "Cameroon",
      listingState: "Centre",
      listingCity: "Ngoa-Ekelle",
      listingStreet: "456 University Ave",
      isSharedBathroom: true,
      bathroomLocation: 'INDOOR',
      isSharedKitchen: true,
      imagePreviews: ["https://via.placeholder.com/400x250?text=Student+Room"],
      images: [],
    },
    {
      id: "103",
      title: "Modern 1-Bedroom Flat",
      description: "A sleek and modern flat in a quiet neighborhood.",
      location: "Bonamoussadi, Douala",
      price: "65000 FCFA",
      roomType: "Entire Apartment",
      rooms: 1,
      toilets: 1,
      kitchen: 1,
      roommates: 0,
      size: "45 sqm",
      listingStyle: 'CONCRETE',
      listingCountry: "Cameroon",
      listingState: "Littoral",
      listingCity: "Douala",
      listingStreet: "789 Bonamoussadi St",
      isSharedBathroom: false,
      bathroomLocation: 'INDOOR',
      isSharedKitchen: true,
      imagePreviews: ["https://via.placeholder.com/400x250?text=Modern+Flat"],
      images: [],
    }
];