spring:
  data:
    elasticsearch:
      repositories:
        enabled: true

  # Kafka (consumer only config)
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: room-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  elasticsearch:
    uris: http://localhost:9200

logging:
  level:
    org.elasticsearch: DEBUG
    org.springframework.data.elasticsearch: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
