spring:
  data:
    elasticsearch:
      repositories:
        enabled: true

  # Kafka (consumer only config)
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 1       # Flush even a single message
#      linger-ms: 0        # No delay
      acks: all           # Ensures durability
      retries: 3          # Good safety net

    consumer:
      group-id: search-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false

  elasticsearch:
    uris: ${ELASTIC_URI}
#    username: ${ELASTIC_USERNAME}
#    password: ${ELASTIC_PASSWORD}

# Logging
logging:
  level:
    org.elasticsearch: INFO

# For deployment
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

