---
- name: Add ingress-nginx Helm repo
  shell: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  args:
    creates: ~/.cache/helm/repository/ingress-nginx-index.yaml

# REMOVED:
# - name: Update Helm repos
#   shell: helm repo update

- name: Create ingress-nginx namespace using kubectl
  shell: |
    kubectl create namespace ingress-nginx --dry-run=client -o yaml | kubectl apply -f -
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Install ingress-nginx via Helm with NodePort (pinned version)
  shell: |
    helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
      --namespace ingress-nginx \
      --version 4.10.0 \
      --set controller.service.type=NodePort \
      --set controller.service.nodePorts.http=30080 \
      --set controller.service.nodePorts.https=30443 \
      --set controller.service.externalTrafficPolicy=Local \
      --set controller.deployment.minReadySeconds=30 \
      --set controller.deployment.progressDeadlineSeconds=60
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
