spring:
  profiles:
    active: dev
  application:
    name: room-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8083