# Kafka (shared for all profiles, can be overridden)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/room8_roomService
    username: root
    password: Test123$
  kafka:
      bootstrap-servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
      admin:
        properties:
          default.replication.factor: 1
          num.partitions: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/