apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
    - port: tcp
      path: /api/actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
