apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-registry
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app: service-registry
  endpoints:
    - port: tcp
      path: /eureka/actuator/prometheus   # ← FIXED
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
