spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      default-filters:
        - AuthenticationFilter
      routes:
        - id: user-service
          uri: http://user-service.default.svc.cluster.local
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: http://auth-service.default.svc.cluster.local
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        - id: room-service
          uri: http://room-service.default.svc.cluster.local
          predicates:
            - Path=/room-service/**
          filters:
            - StripPrefix=1
        - id: search-service
          uri: http://search-service.default.svc.cluster.local
          predicates:
            - Path=/search-service/**
          filters:
            - StripPrefix=1

# For deployment
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/


cors:
  allowed-origins:
    - https://room8.com
    - https://www.room8.com  # if needed

auth-service:
  url: lb://auth-service  # In prod use: http://auth-service.default.svc.cluster.local or lb://auth-service
