spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      default-filters:
        - AuthenticationFilter
      routes:
        - id: user-service
          uri: http://user-service.default.svc.cluster.local
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: http://auth-service.default.svc.cluster.local
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        - id: room-service
          uri: http://room-service.default.svc.cluster.local
          predicates:
            - Path=/room-service/**
          filters:
            - StripPrefix=1
        - id: bid-service
          uri: http://bid-service.default.svc.cluster.local
          predicates:
            - Path=/bid-service/**
          filters:
            - StripPrefix=1
        - id: search-service
          uri: http://search-service.default.svc.cluster.local
          predicates:
            - Path=/search-service/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: http://notification-service.default.svc.cluster.local
          predicates:
            - Path=/search-service/**
          filters:
            - StripPrefix=1

# For deployment
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
    register-with-eureka: true
    fetch-registry: true


cors:
  allowed-origins:
    - ${ALLOWED_ORIGINS_URI}

auth-service:
  url: http://auth-service.default.svc.cluster.local  # In prod use: http://auth-service.default.svc.cluster.local or lb://auth-service
